-- V_EventosProgramados
-- Calendario de eventos programados por recinto
CREATE VIEW V_EventosProgramados AS
SELECT
    E.TITULO_EVENTO,
    R.NOMBRE AS Nombre_Recinto,
    DR.FECHA_HORA_INICIO,
    DR.FECHA_HORA_FIN,
    C.NOMBRE AS Nombre_Cliente,
    TE.TIPO AS Tipo_Evento
FROM
    DETALLE_RECINTOS DR
JOIN EVENTO E ON DR.ID_EVENTO = E.ID_EVENTO
JOIN RECINTO R ON DR.ID_RECINTO = R.ID_RECINTO
JOIN CLIENTE C ON E.ID_CLIENTE = C.ID_CLIENTE
JOIN TIPO_EVENTO TE ON E.ID_TIPO_EVENTO = TE.ID_TIPO_EVENTO
WHERE
    DR.FECHA_HORA_FIN > NOW()
ORDER BY
    DR.FECHA_HORA_INICIO ASC;

-- V_DisponibilidadRecintos
-- Muestra la disponibilidad actual de recintos
CREATE VIEW V_DisponibilidadRecintos AS
SELECT
    R.NOMBRE AS Recinto,
    C.TIPO_CONFIGURACION AS Configuración_Base,
    CFG.CAPACIDAD AS Capacidad_Base,
    DR.ESTADO,
    DR.FECHA_INICIO,
    DR.FECHA_FIN
FROM
    RECINTO R
JOIN CONFIGURACION CFG ON R.ID_CONFIGURACION = CFG.ID_CONFIGURACION
LEFT JOIN DISPONIBILIDAD_RECINTO DR ON R.ID_RECINTO = DR.ID_RECINTO
ORDER BY R.NOMBRE, DR.FECHA_INICIO;

-- V_EquipamientoDisponible
-- Inventario de equipamiento disponible por tipo
CREATE VIEW V_EquipamientoDisponible AS
SELECT
    TE.TIPO AS Tipo_Equipo,
    E.ID_EQUIPAMENTO,
    E.ESTADO,
    E.CANTIDAD_DISPONIBLE,
    A.UBICACION AS Almacenamiento
FROM
    EQUIPAMENTO E
JOIN TIPO_EQUIPAMENTO TE ON E.ID_TIPO_EQUIPAMENTO = TE.ID_TIPO_EQUIPAMENTO
LEFT JOIN ALMACENAMIENTO A ON E.ID_ALMACENAMIENTO = A.ID_ALMACENAMIENTO
WHERE
    E.ESTADO = 'DISPONIBLE'
ORDER BY TE.TIPO, E.CANTIDAD_DISPONIBLE DESC;

-- V_CotizacionesPendientes
-- Lista de cotizaciones aún en estado 'VALIDO' y no convertidas a contrato
CREATE VIEW V_CotizacionesPendientes AS
SELECT
    CT.ID_COTIZACION,
    CT.FECHA_EMISION,
    CT.VALIDEZ,
    C.NOMBRE AS Cliente,
    TE.TIPO AS Tipo_Evento,
    E.TITULO_EVENTO,
    E.PRESUPUESTO_APROBADO
FROM
    COTIZACION CT
JOIN CLIENTE C ON CT.ID_CLIENTE = C.ID_CLIENTE
JOIN TIPO_EVENTO TE ON CT.ID_TIPO_EVENTO = TE.ID_TIPO_EVENTO
LEFT JOIN EVENTO E ON C.ID_CLIENTE = E.ID_CLIENTE AND E.ESTADO_ACTUAL LIKE 'Cotizado%'
WHERE
    CT.VALIDEZ = 'VALIDO'
    AND CT.ID_COTIZACION NOT IN (SELECT ID_CONTRATO FROM CONTRATO);

-- V_AsignacionPersonal
-- Detalle de asignación de personal por evento
CREATE VIEW V_AsignacionPersonal AS
SELECT
    E.TITULO_EVENTO,
    P.NOMBRE AS Nombre_Personal,
    P.APELLIDO AS Apellido_Personal,
    TP.TIPO AS Rol_Base,
    DP.ROL AS Rol_Especifico,
    DP.HORAS_TRABAJADAS,
    DP.TARIFA_HORA,
    DP.SUBTOTAL
FROM
    DETALLE_PERSONAL DP
JOIN EVENTO E ON DP.ID_EVENTO = E.ID_EVENTO
JOIN PERSONAL P ON DP.ID_PERSONAL = P.ID_PERSONAL
JOIN TIPO_PERSONAL TP ON P.ID_TIPO_PERSONAL = TP.ID_TIPO_PERSONAL
ORDER BY E.TITULO_EVENTO, P.APELLIDO;